<a href="https://colab.research.google.com/github/Joongeun/argo_proj/blob/main/Argo_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

#Extract only data points that are within the boundaries of each area
def limitSize(coors, df):
  avgs = []
  #min lon/lat, max lon/lat
  lon1, lat1, lon2, lat2 = coors
  df2 = pd.DataFrame(columns=df.columns)
  for ind in range(len(df)):
    if df["LONGITUDE"][ind] >= lon1 and df["LONGITUDE"][ind] <= lon2:
      if df["LATITUDE"][ind] >= lat1 and df["LATITUDE"][ind] <= lat2:
        df2.loc[len(df2.index)] = list(df.loc[ind])
  return df2

#Find average temp, salinity, and pressure
def findAvg(df):
  a = ["TEMP", "PSAL", "PRES"]
  l = []
  for i in a:
    l.append(df[i].mean())
  return l

#Save the avg. temp, salinity, pressure for years 2010-2020 for each area as a csv file
def saveCSV(l, ind):
  df = pd.DataFrame({"year": l["year"], k: l[k]})
  df.to_csv("avgs_for_area"+str(ind)+".csv")

#Areas 1-5 [min lon, min lat, max lon, max lat]
a = [[-180, -90, -72.61174335, 90], [-72.61174335, 39.9537, -65.29757095, 41.6362], [-72.61174335, -90, -65.29757095, 39.9537], [-65.29757095, 39.9537, 180, 41.6362], [-65.29757095, -90, 180, 39.9537]]
for ind, i in enumerate(a):
  avg = {"temp": [], "salinity": [], "pressure": [], "year": [i for i in range(2010, 2021)]}
  for year in range(2010, 2021):
    df = pd.read_csv("/content/"+str(year)+"_argo.csv")[["TEMP", "PSAL", "PRES", "LONGITUDE", "LATITUDE"]]
    #rectangular areas 1-5 (min lon/lat, max lon/lat) to find avg. temp, salinity, pressure
    df2 = limitSize(i, df)
    t, s, p = findAvg(df2)
    avg["temp"].append(t)
    avg["salinity"].append(s)
    avg["pressure"].append(p)
  print("Area:", ind+1, "done")
  df = pd.DataFrame(avg)
  df.to_csv("avgs_for_area"+str(ind+1)+".csv")

# df[::100].plot(x="TIME", y="TEMP", figsize=(18, 10))
# df.plot(x="TIME", y="TEMP", style = "bx", figsize=(12, 12))

Area: 5 done

In [49]:
#limitSize() function test
df = pd.read_csv("/content/2012_argo.csv")
limitSize(a[0], df)

,N_POINTS,CYCLE_NUMBER,DATA_MODE,DIRECTION,PLATFORM_NUMBER,POSITION_QC,PRES,PRES_ERROR,PRES_QC,PSAL,PSAL_ERROR,PSAL_QC,TEMP,TEMP_ERROR,TEMP_QC,TIME_QC,LATITUDE,LONGITUDE,TIME
0,300,17,A,A,6900109,1,5.200000,NaN,1,36.566002,NaN,1,21.601999,NaN,1,1,32.300,-74.219,2012-01-01 21:36:33
1,301,17,A,A,6900109,1,10.300000,NaN,1,36.566002,NaN,1,21.603001,NaN,1,1,32.300,-74.219,2012-01-01 21:36:33
2,302,17,A,A,6900109,1,14.800000,NaN,1,36.561001,NaN,1,21.538000,NaN,1,1,32.300,-74.219,2012-01-01 21:36:33
3,303,17,A,A,6900109,1,20.000000,NaN,1,36.562000,NaN,1,21.521999,NaN,1,1,32.300,-74.219,2012-01-01 21:36:33
4,304,17,A,A,6900109,1,25.200001,NaN,1,36.562000,NaN,1,21.497000,NaN,1,1,32.300,-74.219,2012-01-01 21:36:33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29829,11447,108,A,A,6900110,1,101.300003,NaN,1,36.636002,NaN,1,24.365999,NaN,1,1,25.237,-73.234,2012-12-31 11:24:34
29830,11448,108,A,A,6900110,1,106.400002,NaN,1,36.750999,NaN,1,24.136999,NaN,1,1,25.237,-73.234,2012-12-31 11:24:34
29831,11449,108,A,A,6900110,1,111.900002,NaN,1,36.779999,NaN,1,23.818001,NaN,1,1,25.237,-73.234,2012-12-31 11:24:34
29832,11450,108,A,A,6900110,1,121.800003,NaN,1,36.825001,NaN,1,23.267000,NaN,1,1,25.237,-73.234,2012-12-31 11:24:34
29833,11451,108,A,A,6900110,1,131.500000,NaN,1,36.790001,NaN,1,22.761000,NaN,1,1,25.237,-73.234,2012-12-31 11:24:34

In [ ]:
# @title Leo's data extraction

import argopy
import pandas as pd

with argopy.set_options(dataset='bgc', src='erddap', mode='expert'):
    f = argopy.DataFetcher(params='all')
    f = f.region([-55, -5, -80, -30, 0, 70, '2023-01-01', '2024-08-06'])
    f.load()
    df = f.to_dataframe()
    df.to_csv("argo_data_2023-present.csv")

In [50]:
#(7/25 - 8/21), (8/23 - 9/3) avg, min, max; avg for 8/22
# @title Charlotte's data analysis
df = pd.read_csv("/content/SEADATAee19be12-e293-5fd1-9cd2-ec5431cc1afa.csv")
df
# var = "chlorophyll"
# for ind, i in enumerate(df[var][1:]):
#   df.at[ind, var] = float(i)
#   if ind % 100000 == 0:
#     print(ind)


# import math
# q = [i for i in df["chlorophyll"] if not math.isnan(i)]
# avg = sum(q) / len(q)
# MIN = min(q)
# MAX = max(q)
# print(avg, MIN, MAX)

,FID,time,profile,depth,segment,distance,trajectory,lat_uv,lon_uv,time_uv,...,qartod_temperature_gross_range_flag,qartod_temperature_primary_flag,qartod_temperature_rate_of_change_flag,qartod_temperature_spike_flag,roll,salinity,temperature,geom,source,source_id
0,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.1,2021-06-20T17:40:36.07,0,7.194283,0,0.000000,0,40.080106,-70.360892,1.624211e+09,...,NaN,NaN,NaN,NaN,1.900003,NaN,NaN,POINT (-70.35950336368973 40.08139979142292),ioos.gliderdac.gliderdac,cp_340-20210620T1735
1,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.2,2021-06-20T17:41:16.028,0,7.194283,0,179.309998,0,40.080106,-70.360892,1.624211e+09,...,NaN,NaN,NaN,NaN,1.900003,NaN,NaN,POINT (-70.36119833333333 40.0804444438218),ioos.gliderdac.gliderdac,cp_340-20210620T1735
2,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.3,2021-06-20T17:41:17.041,0,7.194283,0,179.309998,0,40.080106,-70.360892,1.624211e+09,...,NaN,NaN,NaN,NaN,1.900003,NaN,NaN,POINT (-70.36119833333333 40.08044387735276),ioos.gliderdac.gliderdac,cp_340-20210620T1735
3,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.4,2021-06-20T17:41:19.078,0,7.194283,0,179.440002,0,40.080106,-70.360892,1.624211e+09,...,1.0,1.0,2.0,1.0,1.900003,32.997429,19.8901,POINT (-70.36119833333333 40.08044273779842),ioos.gliderdac.gliderdac,cp_340-20210620T1735
4,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.5,2021-06-20T17:41:36.4,0,7.194283,0,185.500000,0,40.080106,-70.360892,1.624211e+09,...,NaN,NaN,NaN,NaN,1.900003,NaN,NaN,POINT (-70.36123989034225 40.080398508767),ioos.gliderdac.gliderdac,cp_340-20210620T1735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58188,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.58189,2021-07-07T07:18:20.735,2300,28.299128,0,267199.625000,0,40.199699,-70.205628,1.625657e+09,...,NaN,NaN,NaN,NaN,-0.799998,NaN,NaN,POINT (-70.21138812933356 40.17011076151417),ioos.gliderdac.gliderdac,cp_340-20210620T1735
58189,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.58190,2021-07-07T07:18:23.007,2300,37.446884,0,267200.156250,0,40.199699,-70.205628,1.625657e+09,...,1.0,1.0,1.0,1.0,-0.799998,33.020260,8.7946,POINT (-70.21138721959086 40.17011543446565),ioos.gliderdac.gliderdac,cp_340-20210620T1735
58190,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.58191,2021-07-07T07:18:51.143,2300,37.446884,0,267206.625000,0,40.199699,-70.205628,1.625657e+09,...,NaN,NaN,NaN,NaN,-0.799998,NaN,NaN,POINT (-70.21137595712231 40.1701732848548),ioos.gliderdac.gliderdac,cp_340-20210620T1735
58191,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.58192,2021-07-07T07:19:20.467,2300,37.446884,0,267213.406250,0,40.199699,-70.205628,1.625657e+09,...,NaN,NaN,NaN,NaN,-0.799998,NaN,NaN,POINT (-70.21136421862084 40.1702335804174),ioos.gliderdac.gliderdac,cp_340-20210620T1735
58192,ee19be12-e293-5fd1-9cd2-ec5431cc1afa.58193,2021-07-07T07:19:21.496,2300,37.446884,0,267213.656250,0,40.199699,-70.205628,1.625657e+09,...,NaN,NaN,NaN,NaN,-0.799998,NaN,NaN,POINT (-70.2113638067434 40.17023569605217),ioos.gliderdac.gliderdac,cp_340-20210620T1735

In [ ]:
# @title Hayden's data analysis
for ind, i in enumerate(df['sea_water_electrical_conductivity'][1:]):
  df.at[ind, "sea_water_electrical_conductivity"] = float(i)
  if ind % 100000 == 0:
    print(ind)
# df['sea_water_electrical_conductivity'][1:].median()
# min(df['sea_water_electrical_conductivity'])
# max(df['sea_water_electrical_conductivity'])